### ISSUE TITLE
[Little bug] Adding an automatic hyphenation ...

### ISSUE THREAD

**Issue by Jo-Achim** [corona-warn-app/cwa-documentation#785]
## Avoid duplicates
* [X] Bug is not mentioned in the [FAQ](https://www.coronawarn.app/en/faq/)
* [ ] Bug is specific for Android only - **unknown**, for general issues / questions that apply to iOS and Android please raise them in the [documentation repository](https://github.com/corona-warn-app/cwa-documentation)
* [X] Bug is not already reported in another issue

## Technical details

- Android version:  Android 11
- App version:  2.15.1

## Describe the bug

The following example shows the underlying desire for automatic hyphenation:

![grafik](https://user-images.githubusercontent.com/21124877/147577180-2d71c813-50b9-48fe-81e4-41dd6de48630.png)

## Steps to reproduce the issue

1. Create a 'New Event' with Event-Registration and a long Text. 
2. Scan the 'New Event' and see.

## Expected behaviour

This wish actually applies to all dialogues of this type in order to increase readability and, if necessary, to save vertical space. 

---
Internal Tracking ID: [EXPOSUREAPP-11122](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11122)  Android Fix 2.16
Internal Tracking ID: [EXPOSUREAPP-11123](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11123)  iOS Fix ?

**Comment by dsarkar** [comment]
Internal Tracking ID: [EXPOSUREAPP-11122](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11122)  Android
Internal Tracking ID: [EXPOSUREAPP-11123](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-11123)  iOS

**Comment by Jo-Achim** [comment]
Fixed with 2.16.1, thanks and closed.

**Comment by Ein-Tim** [comment]
@Jo-Achim 

Please reopen this issue, it was not fixed under iOS: 

<img src="https://user-images.githubusercontent.com/67682506/149771038-21f3bb0f-3717-4516-9c50-cbb1444ca5bb.png" width="300">

**Comment by Jo-Achim** [comment]
Sorry, I was obviously too quick.

**Comment by Jo-Achim** [comment]
@Ein-Tim, 
has the problem been fixed on iOS in the meantime?
Can it be closed?

**Comment by Ein-Tim** [comment]
@Jo-Achim 

Negative, see:


<img src="https://user-images.githubusercontent.com/67682506/156431145-0e6c1c34-d932-46ee-a0cd-8e4d95aed4cb.jpeg" width="300">


<img src="https://user-images.githubusercontent.com/67682506/156431160-34b6bd7b-5371-48af-9d2e-f6a74f0b6aba.png" width="300">

**Comment by mtwalli** [comment]
@Ein-Tim it is better to create an issue for iOS, I suggest to close this issue for Android

**Comment by Ein-Tim** [comment]
- iOS PR https://github.com/corona-warn-app/cwa-app-ios/pull/4845

The label `Fix 2.28` may be added to this issue.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks.

**Comment by Ein-Tim** [comment]
@dsarkar `Fix 2.16` is also correct as this was the version in which this bug was fixed under Android.

**Comment by dsarkar** [comment]
https://github.com/corona-warn-app/cwa-app-ios/pull/4863

**Comment by Ein-Tim** [comment]
This issue has been fixed. Please close it.

**Comment by dsarkar** [comment]
@Ein-Tim Thanks, @Jo-Achim Thanks for reporting, closing this issue.

---
Best wishes, DS

---
Corona-Warn-App Open Source Team
